#!/bin/bash

set -xe

cd "${1}"

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

PATH=/usr/local/bin:$PATH

PAYLOAD=$(mktemp /tmp/resource-in.XXXXXX)

cat > "$PAYLOAD" <&0

# do stuff

#values from credentials file
apitoken="$(jq -r '.source.apitoken' < "${PAYLOAD}")"
tenanthost="$(jq -r '.source.tenanthost' < "${PAYLOAD}")"

#values from pipeline
monspecserviceenvironment="$(jq -r '.params.monspecserviceenvironment' < "${PAYLOAD}")"
pipelinetaskname="$(jq -r '.params.pipelinetaskname' < "${PAYLOAD}")"
deployversion="$(jq -r '.params.deployversion' < "${PAYLOAD}")"
APP_REPO="$(jq -r '.params.APP_REPO' < "${PAYLOAD}")"

echo "configuring Dynatrace CLI with $apitoken and $tenanthost"

#desired
ls -lrt
python /dtcli/dtcli.py config apitoken $apitoken tenanthost $tenanthost

# path to ci assets:
#./PivotalDevOpsTutorial/ci/

echo "pushing Deployment version $deployversion to service $monspecserviceenvironment defined in $APP_REPO via task $pipelinetaskname"

#desired:
python /dtcli/dtcli.py monspec pushdeploy ./$APP_REPO/ci/smplmonspec.json ./$APP_REPO/ci/smplpipelineinfo.json $monspecserviceenvironment $pipelinetaskname $deployversion

timestamp="$(jq -n "{version:{timestamp:\"$(date +%s)\"}}")"
echo "$timestamp $metadata $debug_info " | jq -s add  >&3
